/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dia7;

import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite a cotação do dólar:");
        float cotacao = leitor.nextFloat();
        
        System.out.println("Digite a quantidade de dólares:");
        float dolar = leitor.nextFloat();
        
        float real = cotacao*dolar;
        
        System.out.println("A quantidade de reais será de " + real + " reais.");
        
     
    }
}
